services:
  # not yet implemented, but planned!
  # db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_DB: botdb
  #     POSTGRES_USER: botuser
  #     POSTGRES_PASSWORD: change_me
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data
  #   restart: unless-stopped

  # redis:
  #   image: redis:7
  #   volumes:
  #     - ./redisdata:/data
  #   restart: unless-stopped

  bot:
    # production
    image: fizzbuzz:latest
    build: .
    env_file: .env
    restart: unless-stopped
    # depends_on: [db, redis]
    # keep logs modest so they don't fill disk
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - prod
    volumes:
      - ./data:/app/data # so db data persists

  bot-test:
    image: fizzbuzz:latest
    build: .
    env_file: .env.test
    restart: no
    entrypoint: [ "/bin/sh", "-lc", "python -m fizzbuzz --token-override \"$$TESTING_TOKEN\" --debug --show-env" ]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - test
    volumes:
      - ./test_data:/app/data
